name: Validate Pull Request

on:
  pull_request:
    paths:
    - '**.rb'

jobs:
  validate:
    runs-on: ubuntu-latest
    # strategy:
    #   matrix:
    #     ruby: ['2.5', '2.7']
    steps:
    - name: Git clone
      uses: actions/checkout@v2
      with:
        fetch-depth: 2
    - name: Setup Ruby
      uses: actions/setup-ruby@v1
      with:
        # ruby-version: ${{ matrix.ruby }}
        ruby-version: '2.7'
    - uses: actions/cache@v2
      with:
        path: vendor/bundle
        key: ${{ runner.os }}-gems-${{ hashFiles('**/Gemfile.lock') }}
        restore-keys: |
          ${{ runner.os }}-gems-
    - name: Bundle install
      run: |
        bundle config path vendor/bundle
        bundle install --jobs 4 --retry 3
    - name: Run lint
      run: bundle exec rake lint
    - name: Run tests
      run: bundle exec rake spec
